import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import { Sidebar } from "@/components/Sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" data-theme="night">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          
          <SignedIn>
            <div className="flex min-h-screen bg-base-100 text-base-content">
              <Sidebar />
              <div className="flex-1 md:ml-56 p-4">{children}</div>
            </div>
          </SignedIn>

          <SignedOut>
            <div
              className="relative flex items-center justify-center min-h-screen bg-cover bg-center"
              style={{ backgroundImage: "url('/bg.png')" }}>
              <div className="absolute inset-0 bg-black/50"></div> 
              <div className="relative z-10 p-8 shadow-xl rounded-lg text-center max-w-sm w-full bg-neutral bg-opacity-60 backdrop-blur-md">
              {/* <div className="relative z-10 p-8 shadow-xl rounded-lg text-center max-w-sm w-full"> */}
                {children}
              </div>
            </div>
          </SignedOut>
          
        </body>
      </html>
    </ClerkProvider>
  );
}

